### PR TITLE
Build JNI libraries on gradle build

### PR DESCRIPTION
**Pull request by Lance0312**

### CODE REVIEW

**Comment by andriydruk** [comment]
I would prefer local.properties ndk.dir instead of global variables

>     Properties properties = new Properties()
>     properties.load(project.rootProject.file('local.properties').newDataInputStream())
>     def ndk_command_path = properties.getProperty('ndk.dir')

**Comment by Lance0312** [comment]
I have refined the script to use `ndk.dir` from local.properties, check it out!

**Comment by andriydruk** [comment]
Thank for your contribution!

**Comment by Lance0312** [comment]
Thank you!

**Pull request merged**
